### PR TITLE
changed variable name based on functionality

### PR DESCRIPTION
**Pull request by jaykay99992**
fchanged variable name "seems_fishy" to "template_number_issue" to represent the use case of the variable for clarity

### CODE REVIEW

**Comment by Louqman-ETS** [comment]
I agree with that, changing the variable name from "seems_fishy" to "template_number_issue" to represent the use case of the variable is a good programming practice to improve code readability and understanding. Just can you add 'is' because its a boolean?

**Comment by jaykay99992** [comment]
@Louqman-ETS good remark, i just changed the variable name to is_template_number_issue to show it's boolean nature. Do i merge it like this ?

**Comment by Louqman-ETS** [comment]
@jaykay99992 Yes, you can merge this branch.

**Comment by jaykay9999** [comment]
code approved and merged

**Pull request merged**
